#!/bin/bash
cd $HOME
    mv mb $PREFIX/bin/mb
    chmod +x $PREFIX/bin/mb
clear
echo -e "\033[1;32mSEJAM CONSCIENTES, A DIVULGAÇÃO DE MÉTODOS NAS REDES SOCIAIS SÃO PREJUDICIAIS PARA TODOS QUE SE BENEFICIAM DA NET FREE. NÃO SEJAM NOOBS, PRESERVEM :)\033[1;37m"
echo -e "\033[1;31mHORARIO QUE GERALMENTE FUNCIONA 7-12AM\033[1;37m"

echo "INFORME SEU NÚMERO (DDD+NÚMERO)"
read NUMERO
echo "QUANTIDADE DE VEZES (1GB = 20)"
read VEZES
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=4919b47c-f588-4e71-87e3-639b3af92e4d&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo ""
echo -e "\033[1;32mCONTAGEM:\033[1;37m$i"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mPARA INICIAR NOVAMENTE DIGITE: \033[1;32mmb\033[0m"
