#!/bin/bash
cd $HOME
    mv mb2 $PREFIX/bin/mb2
    chmod +x $PREFIX/bin/mb2
clear
echo -e "\033[1;32mSEJAM CONSCIENTES, A DIVULGAÇÃO DE MÉTODOS NAS REDES SOCIAIS SÃO PREJUDICIAIS PARA TODOS QUE SE BENEFICIAM DA NET FREE. NÃO SEJAM NOOBS, PRESERVEM :)\033[1;37m"
echo -e "\033[1;31mTRUE = APROVADO , FALSE = REPROVADO\033[1;37m"
echo "INFORME SEU TOKEN"
read TOKEN
echo "INFORME SEU NÚMERO (DDD+NÚMERO)"
read NUMERO
echo "QUANTAS VEZES DESEJA REPETIR?"
read VEZES
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo ""
echo -e "\033[1;32mCONTAGEM:\033[1;37m$i"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mPARA INICIAR NOVAMENTE DIGITE: \033[1;32mmb2\033[0m"
